---
  GrafanaMetrics.push_metric_locally:
    {% set pushgateway_port = pushgateway_port or 9091 %}
    {% set grafana_port = grafana_port or 3000 %}
    {% set sleep_time = sleep_time or 5 %}
    {% set retries_total = retries_total or 30 %}
    -
      args:
        monitor_vip: {{ monitor_vip }}
        pushgateway_port: {{ pushgateway_port }}
        grafana:
          user: {{ grafana_user }}
          password: {{ grafana_password }}
          port: {{ grafana_port }}
        datasource_id: {{ datasource }}
        job_name: rally-test
        sleep_time: {{ sleep_time }}
        retries_total: {{ retries_total }}
      runner:
        type: "constant"
        times: {{ compute }}
        concurrency: {{ concurrency }}
      context:
        users:
          tenants: 1
          users_per_tenant: 1
      sla:
        failure_rate:
          max: 0